// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5RBmEvEfCZFbd94VdXQCxCeMc8_HqUt0',
    appId: '1:788897835705:web:c3d9646b1bfb3cee530968',
    messagingSenderId: '788897835705',
    projectId: 'project-showcase-app',
    authDomain: 'project-showcase-app.firebaseapp.com',
    storageBucket: 'project-showcase-app.appspot.com',
    measurementId: 'G-MEQ849V0M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGZog2TQYiSyudnVIFEpnBT7l77cjcmVY',
    appId: '1:788897835705:android:2ef614ccb504b78e530968',
    messagingSenderId: '788897835705',
    projectId: 'project-showcase-app',
    storageBucket: 'project-showcase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfRJtyvdiR36rDzkIB_AcaFkI_pfQJJYc',
    appId: '1:788897835705:ios:7124330349ae7871530968',
    messagingSenderId: '788897835705',
    projectId: 'project-showcase-app',
    storageBucket: 'project-showcase-app.appspot.com',
    iosBundleId: 'com.example.projectShowcase',
  );
}
